#! /bin/bash

touch tmp.txt

for file in "${@}"

do
startime=$(cat ${file} |head -n 2| tail -n 1 | cut -f 1 -d " ")

cat ${file} | tail -n +2| gawk -v  "x=${startime}" 'x +10000 > $1, NF > 1 {print $2, $3}' >> tmp.txt

xavg=$(cat ${file} | gawk -v  "x=${startime}" 'x +10000 > $1, NF > 1 {print $2}' | tail -n +2 | ./../scripts/average.py) 
yavg=$(cat ${file} | gawk -v  "x=${startime}" 'x +10000 > $1, NF > 1 {print $3}' | tail -n +2 | ./../scripts/average.py)

xstddev=$(cat ${file} | gawk -v  "x=${startime}" 'x +10000 > $1, NF > 1 {print $2}' | tail -n +2 | ./../scripts/stddev)
ystddev=$(cat ${file} | gawk -v  "x=${startime}" 'x +10000 > $1, NF > 1 {print $3}' | tail -n +2 | ./../scripts/stddev)
Tstddev=$(echo "sqrt((${xstddev}^2)+(${ystddev}^2))" | bc)

echo "${file} ${xavg} ${yavg} ${xstddev} ${ystddev} ${Tstddev}"
done

