#! /bin/bash


for file in "${@}"

do
startime=$(cat ${file} |head -n 2| tail -n 1 | cut -f 1 -d " ")

xavg=$(cat ${file} | gawk -v  x="${startime}" 'x +10000 > $1, NF > 1 {print $2}' | tail -n +2 | ./../scripts/average.py)
yavg=$(cat ${file} | gawk -v  x="${startime}" 'x +10000 > $1, NF > 1 {print $3}' | tail -n +2 | ./../scripts/average.py)

cat ${file} | tail -n +2| gawk -v t="${startime}" -v x="${xavg}" -v y="${yavg}" ' t + 10000 > $1, NF > 1 {print sqrt(($2-x)^2 + ($3-y)^2)}'
done
