#! /bin/bash

for file in "${@}"

do
xavg=$(cat ${file} | gawk 'NF > 1 {print $2}' | tail -n +2 | ./../scripts/average.py) 
yavg=$(cat ${file} | gawk 'NF > 1 {print $3}' | tail -n +2 | ./../scripts/average.py)

xstddev=$(cat ${file} | gawk 'NF > 1 {print $2}' | tail -n +2 | ./../scripts/stddev)
ystddev=$(cat ${file} | gawk 'NF > 1 {print $3}' | tail -n +2 | ./../scripts/stddev)
Tstddev=$(echo "sqrt((${xstddev}^2)+(${ystddev}^2))" | bc)

echo "${file} ${xavg} ${yavg} ${xstddev} ${ystddev} ${Tstddev}"
done | column -t
