#! /bin/bash

for file in "${@}"

do
starttime=$(cat ${file} | head -n 2 | tail -n 1 | cut -f 1 -d " ")
xavg=$(cat ${file} | gawk -v x="${starttime}" '$1 < x + 10000, NF > 1 {print $2}' | tail -n +2 | ./avg.py)

xdis=$(cat ${file} | gawk -v x="${starttime}" '$1 < x + 10000, NF > 1 {print $2}' | gawk -v x="${xavg}" '{diff = x - $1}; {xsq = diff**2}; { print xsq }')
