#! /usr/bin/python

import fileinput

import argparse

parser = argparse.ArgumentParser(description="Calculate the average of column data.")

parser.add_argument("files", metavar="FILE", nargs="*", help="input files. stdin is used if no files are given.")
args = parser.parse_args()

delim=' '
sum = []
num = []
for line in fileinput.input(files=args.files if len(args.files) > 0  else ('-',) ):
  fields = line.split(delim)
  for i in range(len(fields)):
    try:
      x = float(fields[i])
      if i == len(sum):
        sum.append(0)
      if i == len(num):
        num.append(0)

      sum[i] += x
      num[i] += 1

    except:
      pass

line = ""
for i in range(len(sum)):
  line += " " + str(sum[i]/num[i])
print line.strip()
