#! /usr/bin/python

import fileinput, math

import argparse

parser = argparse.ArgumentParser(description="Calculate the standard deviation of column data.")

parser.add_argument("--biased", "-b", action="store_true", help="use biased estimator (divide by n instead of n - 1)")
parser.add_argument("files", metavar="FILE", nargs="*", help="input files. stdin is used if no files are given.")
args = parser.parse_args()

delim=' '
avg= []
sum = []
num = []
for line in fileinput.input(files=args.files if len(args.files) > 0  else ('-',) ):
  fields = line.split(delim)
  for i in range(len(fields)):
    try:
      x = float(fields[i])
      if i == len(avg):
        avg.append(0)
      if i == len(sum):
        sum.append(0)
      if i == len(num):
        num.append(0)

      num[i] += 1
      delta = x - avg[i]
      avg[i] += delta/num[i]
      delta2 = x - avg[i]
      sum[i] += delta*delta2
    except:
      pass

line = ""
for i in range(len(sum)):
  if num[i] < 2:
    line += "nan"
  else:
    N = num[i]
    if not args.biased:
      N = N - 1
    line += " " + str(math.sqrt(sum[i]/N))
print line.strip()
